server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    time-zone: Asia/Seoul

spring:
  application:
    name: portiony

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
    database: mysql
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  profiles:
    active: dev
    include:
      - database

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            redirect-uri: https://portiony.netlify.app/login/oauth/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  accessExpiration: 86400000 #1일 > 테스트용, 테스트 후 수정 필요
  refreshExpiration: 2592000000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

frontend:
  domain: ${FRONT_DOMAIN}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: eu-central-1
    s3:
      bucket: portiony-bucket
    stack:
      auto: false
#frontend:
#  domain: ${FRONT_DOMAIN}
#redis:
#  domain: ${REDIS_DOMAIN}

portiony:
  location:
    init:
      enabled: true