server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: portiony
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
    database: mysql
  profiles:
    include:
      - database
      - local

#frontend:
#  domain: ${FRONT_DOMAIN}
#
#jwt:
#  secret: ${JWT_SECRET}
#
#redis:
#  domain: ${REDIS_DOMAIN}