server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: portiony

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: update
    database: mysql
  profiles:
    include:
      - database
      - local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            redirect-uri: http://localhost:8080/api/users/login/oauth/kakao/callback
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#frontend:
#  domain: ${FRONT_DOMAIN}
#

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  accessExpiration: 3600000
  refreshExpiration: 2592000000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

#frontend:
#  domain: ${FRONT_DOMAIN}
#redis:
#  domain: ${REDIS_DOMAIN}